chore(Slack)[WIP]: try without external action

diff --git a/.github/workflows/notify.yml b/.github/workflows/notify.yml
--- a/.github/workflows/notify.yml
+++ b/.github/workflows/notify.yml
@@ -35,9 +35,20 @@ jobs:
           MATTERMOST_ICON: "https://github.com/Orange-OpenSource.png"
 
       - name: Notify slack
-        uses: pullreminders/slack-action@master
+        run: |
+          set -eu
+
+          if [[ -z "$SLACK_BOT_TOKEN" ]]; then
+            echo "Missing SLACK_BOT_TOKEN secret."
+            exit 1
+          fi
+
+          curl -X POST \
+               -H "Content-type: application/json" \
+               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
+               -d $SLACK_BOT_MESSAGE \
+               https://slack.com/api/chat.postMessage
         if: github.event_name == 'push'
-        with:
-          args: '{\"channel\":\"CTDKAU5CZ\",\"text\":\"Release ${{ github.event.pull_request.number }} :tada:\n<${{ github.event.pull_request.html_url }}|Changelog> — <${{ github.event.pull_request.html_url }}|Download (zip)>\"}'
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+          SLACK_BOT_MESSAGE: "{\"channel\":\"CTDKAU5CZ\",\"text\":\"Release ${{ github.event.pull_request.number }} :tada:\n<${{ github.event.push.compare }}|Changelog> — <${{ github.event.push.compare }}|Download (zip)>\"}"
